name: watchtower

services:
  watchtower:
    container_name: watchtower
    image: containrrr/watchtower
    network_mode: nginx
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - TZ = "Europe/Paris"
      - WATCHTOWER_CLEANUP = "true"
      - WATCHTOWER_SCHEDULE = "0 0 4 * * *"
