services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    networks:
      - proxy
    labels:
      - traefik.enable=true
      - traefik.http.routers.jellyfin-https.tls=true
      - traefik.http.routers.jellyfin-https.tls.certresolver=myresolver
      - traefik.http.routers.jellyfin-https.entrypoints=websecure
      - traefik.http.routers.jellyfin-https.rule=Host(`jellyfin.maxlttr7.duckdns.org`)
      - traefik.http.services.jellyfin-https.loadbalancer.server.port=8096
    environment:
      - PUID=1001
      - PGID=100
      - TZ=Etc/UTC
    volumes:
      - ${HOME}/docker/jellyfin/library:/config
      - ${HOME}/docker/movies:/data/movies
      - ${HOME}/docker/tvshows:/data/tvshows
      - ${HOME}/Syncthing/music:/data/music:ro
    ports:
      - 8096:8096
    devices:
      - /dev/dri:/dev/dri
    restart: unless-stopped

networks:
  proxy:
    external: true