services:
  suaps:
    image: ghcr.io/flash2974/reservercreneausuaps-app:latest
    volumes:
      - ${HOME}/docker/suaps/config.json:/app/config/config.json
    env_file:
      - ${HOME}/.config/sops-nix/secrets/suaps.env
    ports:
      - 5000:5000
    restart: unless-stopped
